// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class AMAppInfo {
  AMAppInfo({
    required this.handle,
    required this.name,
    required this.iconData,
    required this.category,
  });

  int handle;

  String name;

  Uint8List iconData;

  String category;

  Object encode() {
    return <Object?>[
      handle,
      name,
      iconData,
      category,
    ];
  }

  static AMAppInfo decode(Object result) {
    result as List<Object?>;
    return AMAppInfo(
      handle: result[0]! as int,
      name: result[1]! as String,
      iconData: result[2]! as Uint8List,
      category: result[3]! as String,
    );
  }
}

class ServerApi {
  /// Constructor for [ServerApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ServerApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  Future<String> getPlatformVersion() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.headunit.ServerApi.getPlatformVersion', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<void> startServer() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.headunit.ServerApi.startServer', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _HeadunitApiCodec extends StandardMessageCodec {
  const _HeadunitApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is AMAppInfo) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return AMAppInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class HeadunitApi {
  static const MessageCodec<Object?> codec = _HeadunitApiCodec();

  void amRegisterApp(AMAppInfo appInfo);

  void amUnregisterApp(String name);

  static void setup(HeadunitApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.headunit.HeadunitApi.amRegisterApp', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.headunit.HeadunitApi.amRegisterApp was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final AMAppInfo? arg_appInfo = (args[0] as AMAppInfo?);
          assert(arg_appInfo != null,
              'Argument for dev.flutter.pigeon.headunit.HeadunitApi.amRegisterApp was null, expected non-null AMAppInfo.');
          api.amRegisterApp(arg_appInfo!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.headunit.HeadunitApi.amUnregisterApp', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.headunit.HeadunitApi.amUnregisterApp was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_name = (args[0] as String?);
          assert(arg_name != null,
              'Argument for dev.flutter.pigeon.headunit.HeadunitApi.amUnregisterApp was null, expected non-null String.');
          api.amUnregisterApp(arg_name!);
          return;
        });
      }
    }
  }
}
