name: build

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.1"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Test
        run: cd app && flutter test
      - name: Build for Web
        run: cd app && flutter build web
